config/routes.rb
Platenation::Application.routes.draw do
  root :to => 'pages#home'

  devise_for :users

  resources :profiles, :only => [:show, :new, :create, :index, :edit, :update]
  resources :addresses, :only => [:show, :new, :create, :index, :edit, :update]
  

  match '/help',    to: 'pages#help'
  match '/about',   to: 'pages#about'
  match '/contact',   to: 'pages#contact'

  

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :line1, :line2, :city, :state, :zip, :profile_id
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :phone, :user_id, :address_attributes
  has_one :address
  accepts_nested_attributes_for :address
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, 
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  
  def new
    @address = Address.new
  end

  def edit
     @address = Address.find(params[:id])
  end

  def create
    @address = Address.new(params[:address])
    if @address.save
      redirect_to @address, notice: "Successfully created address."
    else
      render 'new'
    end
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(params[:address])
      flash[:notice] = "You updated your address!"
      redirect_to @address
    else
      render 'edit'
    end
  end

  def index
    @address = Address.all
  end

  def show
    @address = Address.find(params[:id])
  end
 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def new
    @profile = Profile.new
    @profile.build_address
  end

  def edit
     @profile = Profile.find(params[:id])
  end

  def create
    @profile = Profile.new(params[:profile])
    if @profile.save
      redirect_to @profile, notice: "Successfully created profile."
    else
      render 'new'
    end
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update_attributes(params[:profile])
      flash[:notice] = "You updated your profile!"
      redirect_to @profile
    else
      render 'edit'
    end
  end

  def index
    @profile = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end
 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/addresses/new.html.erb
<h1>CREATE YOUR ADDRESS</h1>

<%= form_for @address do |f| %>

  <div><%= f.label :line1 %><br />
  <%= f.text_field :line1 %></div>
 
  <div><%= f.label :line2 %><br />
  <%= f.text_field :line2 %></div>

  <div><%= f.label :city %><br />
  <%= f.text_field :city %></div>

  <div><%= f.label :state %><br />
  <%= f.text_field :state %></div>

  <div><%= f.label :zip %><br />
  <%= f.text_field :zip %></div>



  <div><%= f.submit "Create Address" %></div>
<% end %>

app/views/addresses/show.html.erb
<h1>THIS IS YOUR ADDRESS</h1>

        
	Your line1: <%= @address.line1 %><br />
	Your line2: <%= @address.line2 %><br />
	Your city: <%= @address.city %><br />
	Your state: <%= @address.state %><br />
	Your zip: <%= @address.zip %><br />

app/views/layouts/_address.html.erb
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>

<p>
  <%= f.label :line1, 'Address 1' %><br />
  <%= f.text_field :line1 %>
</p>

<p>
  <%= f.label :line2, 'Address 2' %><br />
  <%= f.text_field :line2 %>
</p>

<p>
  <%= f.label :city %><br />
  <%= f.text_field :city %>
</p>

<p>
  <%= f.label :state %><br />
  <%= f.text_field :state, :size => 2 %>
</p>

<p>
  <%= f.label :zip, 'Zip Code' %><br />
  <%= f.text_field :zip %>
</p>

<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer container">
  <nav>
    <ul>
      <li><%= link_to "FAQ",   help_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>

  <small>
  © 2012 Plate Nation. All rights reserved. A startup weekend project, coded with aloha.
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
	<div id="HOLDnav" class="container navbar navbar-fixed-top">
		<div id="user_nav" class="pull-left">
		    <% if user_signed_in? %>
		        Signed in as <%= current_user.email %>. Not you?
		        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
		    <% else %>
		        <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
		    <% end %>
			</div>
			<div id="user_nav" class="pull-right">
		    <% if user_signed_in? %>
		        <%= link_to 'Account Profile', edit_user_registration_path %>
		    <% else %>
		    <% end %>
		</div>
	</div>	
	    <header class="row">
	    	<div class="span2 offset2 header-link right">        
	            <%= link_to "How it works", "/#how-it-works", class: "howitworks" %>
	        </div>
	        <div class="span4 center">    
	        	<hgroup class="logo">
	        		<h1><%= link_to "Home", root_path %></h1>
	       		</hgroup>
	        </div>  	
	        <div class="span2 header-link left">
	        	<%= link_to "Sign Up Free", new_user_registration_path %>
	        </div>	
	    </header>
        <%= render 'layouts/messages' %>
       <!-- <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p> -->

	</div>

app/views/layouts/_messages.html.erb
<!-- <% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %> -->

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
 <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>

    

    <div class="container bodycontainer">

      	<%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
STUFFSTUFFSTUFF
</p>

app/views/pages/contact.html.erb
<% provide(:title, 'About') %>
<h1>Contact</h1>
<p>
contactSTUFFcontactSTUFFcontactSTUFF
</p>

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>FAQ</h1>

<br />
<h2>What is Plate Nation? </h2>
<p>Plate Nation is a network of people who love the experience of sharing a home cooked meal with locals around the globe. Plate Nation is for the food lover looking to meet new people when they go to a new city. It's for someone looking to meet new people over good food and conversation.</p> 
<p>All of us on the Plate Nation team know what its like to have those incredible travel experiences over a meal. The taste of the food, the laughter, the cultural exchange—it's something you never forget. We want to ensure that is possible wherever you're going. Add to that that every meal you have on Plate Nation, we give another meal to someone in America that needs it most. Meal for meal.</p>

<p>All of this is why we're passionate about Plate Nation. To make the world smaller, one plate at a time. </p>

<br />
<h2>How do I use Plate Nation? </h2>
<p>First things first: register and create a profile (link). Then, add some photos and descriptive information about your interests, food, and personality. This will help other Plate Nation citizens see that you’re an amazing person to share a meal with, whether you're the traveler or the meal host. </p>

<p>After you have your profile up and running, you can search Plate Nation for people all over the world willing to share a meal with you. Once you find the person who you want to share a meal with them, simply send them a message and let them know when you're thinking. Be sure to tell each person why you want to share a meal with them as opposed to another Plate Nation citizen. After all, these great people could be making one of their favorite dishes for you, so tell them why you're excited for the experience! </p>

<br />
<h2>Where are Plate Nation citizens located?</h2>
<p>As we have just launched Plate Nation, we are looking to build up the network in every city around the world. The best way to get Plate Nation in your city is to sign up (link) and start sharing meals! If you would like to be a Plate Nation representative in your city, let us know and we'll hook you up (email link). </p>

<br />
<h2>How much does it cost to use Plate Nation?</h2>
<p>Plate Nation is completely free. However, we do suggest that you have your physical address verified with us at least once per year (costs around $25). This will make other Plate Nation citizens more comfortable with sharing a meal with you. </p>

<br />
<h2>Do I pay anything to the hosts when I share meal with them?</h2>
<p>We ask that you treat other Plate Nation citizens like you would if you were going over to a friends house for dinner. Chipping in for the cost food, bringing a small gift as a token of appreciation, even checking beforehand if they need anything from the store, are all encouraged when sharing a meal. These people are opening up their homes just for you, let them know how grateful you are. </p>

<br />
<h2>How do Plate Nation citizens stay safe?</h2>
<p>Trust is the foundation of sharing meals with everyone on Plate Nation. Helping you stay safe is our top priority.</p>

<br />
<h2>Facebook verification</h2>
<p>Sign in with Facebook and discover your trusted connections to hosts and guests all over the world. In fact, on every search results page, we'll tell you if you have any mutual friends with people sharing a meal in that city. </p>


<br />
<h2>Experience reviews: </h2>
<p>After sharing a meal, the host or the visitor can rate their experiences as positive or negative. Additionally, we encourage people to tell a little bit about their experience in the review following the meal. The more you tell, the more informed other Plate Nation citizens down the road. </p>

<br />
<h2>Address verification:</h2> 
<p>We also offer an optional verification system that confirms individuals’ names and addresses. Those who opt in are identified with a check mark icon and are featured higher up in Plate Nation search results (difficulty in doing that?).</p>

<br />
<h2>LinkedIn Verification </h2>
<p>You can now connect your Plate Nation profile with the world’s largest professional network. Connecting with LinkedIn builds confidence between guests and hosts by establishing a link to your professional life.</p>

<br />
<h2>Twitter Verification </h2>
<p>Validate your Plate Naton account and add another level of trust to your profile.</p>

<br />
<h2>SMS Verification</h2>
<p>Make it easier to communicate with a verified phone number. We’ll send you a code by SMS or read it to you over the phone. Enter the code below to confirm that you’re the person on the other end.</p>

<p>Most importantly, taking the time to read the profiles very carefully to make sure they’ve been verified (the more ways the better) and that there’s a personality match is critical to safety and a positive experience when sharing a meal. </p>

app/views/pages/home.html.erb
<div class="center">
  <h1>Welcome to Platenation!</h1>

<h3>Look at all these idiots</h3>
<div class="tiles">
	<div class="row">
		
	</div>
</div>
<hr>
<div class="row" id="how-it-works">
	<div class="span12 center">
		<h2 class="heading">How it Works</h2>
			<%= link_to image_tag("howitworks.png")%>
	</div>
</div>

</div>

app/views/profiles/edit.html.erb
<h1>Edit YOUR PROFILE</h1>


<%= form_for @profile do |f| %>

  <div><%= f.label :first_name %><br />
  <%= f.text_field :first_name %></div>
 
  <div><%= f.label :last_name %><br />
  <%= f.text_field :last_name %></div>

  <div><%= f.label :phone %><br />
  <%= f.text_field :phone %></div>
	
	  <%= f.fields_for :address do |builder| %>
	  	<div><%= builder.label :line1 %><br />
		<%= builder.text_field :line1 %></div>
 	 	<div><%= builder.label :line2 %><br />
  		<%= builder.text_field :line2 %></div>
   		<div><%= builder.label :city %><br />
 		<%= builder.text_field :city %></div>   		
 		<div><%= builder.label :state %><br />
 		<%= builder.text_field :state %></div>   		
 		<div><%= builder.label :zip %><br />
 		<%= builder.text_field :zip %></div>
	  <% end -%>
  

  <div><%= f.submit "UPDATE Profile" %></div>
<% end %>

app/views/profiles/new.html.erb
<h1>CREATE YOUR PROFILE</h1>

<%= form_for @profile do |f| %>

  <div><%= f.label :first_name %><br />
  <%= f.text_field :first_name %></div>
 
  <div><%= f.label :last_name %><br />
  <%= f.text_field :last_name %></div>

  <div><%= f.label :phone %><br />
  <%= f.text_field :phone %></div>

	  <%= f.fields_for :address do |builder| %>
	  	<div><%= builder.label :line1 %><br />
		<%= builder.text_field :line1 %></div>
 	 	<div><%= builder.label :line2 %><br />
  		<%= builder.text_field :line2 %></div>
   		<div><%= builder.label :city %><br />
 		<%= builder.text_field :city %></div>   		
 		<div><%= builder.label :state %><br />
 		<%= builder.text_field :state %></div>   		
 		<div><%= builder.label :zip %><br />
 		<%= builder.text_field :zip %></div>
	  <% end -%>
  
  <div><%= f.submit "Create Profile" %></div>
<% end %>

app/views/profiles/show.html.erb
<h1>THIS IS YOUR PROFILE</h1>

        
	Your first name: <%= @profile.first_name %><br />
	Your last name: <%= @profile.last_name %><br />
	Your phone number: <%= @profile.phone %><br />
	Your Address: <%= @profile.address.line1 %> <%= @profile.address.line2 %><br />
	Your phone number: <%= @profile.address.city %>, <%= @profile.address.state %> <%= @profile.address.zip %> 